name: flutter_core_example
description: "Demonstrates how to use the flutter_core plugin."
publish_to: "none"

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_core:
    path: ../

  cupertino_icons: ^1.0.6
  flutter_localization: ^0.2.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  very_good_analysis: ^6.0.0
  patrol: ^3.14.0

dependency_overrides:
  meta: ^1.15.0

flutter:
  uses-material-design: true

  assets:
    - ../assets/


patrol:
  app_name: Example App
  android:
    package_name: com.flutter.flutter_core_example
  ios:
    bundle_id: com.flutter.flutter_core_example

