name: flutter_core
description: "Flutter Core Project"
version: 2.0.4

publish_to: "none"

environment:
  sdk: ">=3.10.8 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0
  intl: ^0.20.2
  collection: ^1.18.0
  dio: ^5.7.0
  sqflite: ^2.4.0
  shared_preferences: ^2.2.3

  #ui
  animations: ^2.0.7
  cupertino_icons: ^1.0.8

  #utils
  device_info_plus: ^12.1.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.3
  share_plus: ^12.0.0
  url_launcher: ^6.3.1
  app_settings:
    path: local_packages/app_settings-6.1.1

  #encryption
  encrypt: ^5.0.3
  permission_handler: ^12.0.0+1
  in_app_update: ^4.2.3

  #firebase
  firebase_remote_config: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0
  sqflite_common_ffi: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.flutter.flutter_core
        pluginClass: FlutterCorePlugin
      ios:
        pluginClass: FlutterCorePlugin
      linux:
        pluginClass: FlutterCorePlugin
      macos:
        pluginClass: FlutterCorePlugin
      windows:
        pluginClass: FlutterCorePluginCApi
      web:
        pluginClass: FlutterCoreWeb
        fileName: flutter_core_web.dart

  assets:
    - assets/
